# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
on:
  push:
    branches:
      ["master"]
    paths:
     ["api/**"]
  pull_request:
    branches:
      ["master"]
    paths:
      ["api/**"]

jobs:
  api:
    name: Build & Test API
    runs-on: self-hosted
    if: contains(github.event.head_commit.modified, 'api/')
    defaults:
      run:
        working-directory: api
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build API
        run: npm run build

  client:
    name: Build & Test Client
    runs-on: selft-hosted
    if: contains(github.event.head_commit.modified, 'client/')
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Client
        run: npm run build
