# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
on:
  push:
    branches:
      ["master"]
  pull_request:
    branches:
      ["master"]

jobs:
  check-changes:
    runs-on: self-hosted
    outputs:
      api_changed: ${{ steps.filter.outputs.api }}
      client_changed: ${{ steps.filter.outputs.client }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Changed Files
        id: filter
        run: |
          API_CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^api/' || true)
          CLIENT_CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^client/' || true)

          echo "api=${API_CHANGED:+true}" >> $GITHUB_OUTPUT
          echo "client=${CLIENT_CHANGED:+true}" >> $GITHUB_OUTPU
  
  api:
    name: Build & Test API
    runs-on: self-hosted
    needs: check-changes
    if: needs.check-changes.outputs.api_changed == 'true'
    defaults:
      run:
        working-directory: api
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build API
        run: npm run build

  client:
    name: Build & Test Client
    runs-on: selft-hosted
    needs: check-changes
    if: needs.check-changes.outputs.client_changed == 'true'
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Client
        run: npm run build
